module.exports = [ { text: '“All we have to decide is what to do with the time that is given us.”',
    authorOrTitle: 'J.R.R. Tolkien' },
  { text: '“We can\'t be afraid of change. You may feel very secure in the pond that you are in, but if you never venture out of it, you will never know that there is such a thing as an ocean, a sea. Holding onto something that is good for you now, may be the very reason why you don\'t have something better.”',
    authorOrTitle: 'C. JoyBell C.' },
  { text: '“Don\'t let the muggles get you down.”',
    authorOrTitle: 'J.K. Rowling' },
  { text: '“How would your life be different if…You walked away from gossip and verbal defamation? Let today be the day…You speak only the good you know of other people and encourage others to do the same.”',
    authorOrTitle: 'Steve Maraboli' },
  { text: '“Our chief want is someone who will inspire us to be what we know we could be.”',
    authorOrTitle: 'Ralph Waldo Emerson' },
  { text: '“You cannot expect victory and plan for defeat.”',
    authorOrTitle: 'Joel Osteen' },
  { text: '“Everything will be okay in the end. If it\'s not okay, then it\'s not the end.”',
    authorOrTitle: 'Ed Sheeran' },
  { text: '“Thankfully, persistence is a great substitute for talent.”',
    authorOrTitle: 'Steve Martin' },
  { text: '“You can get a thousand no\'s from people, and only one "yes" from God.”',
    authorOrTitle: 'Tyler Perry' },
  { text: '“It\'s just that in the Deep South, women learn at a young age that when the world is falling apart around you, it\'s time to take down the drapes and make a new dress.”',
    authorOrTitle: 'Karen Marie Moning' },
  { text: '“Yelling at living things does tend to kill the spirit in them. Sticks and stones may break our bones, but words will break our hearts...”',
    authorOrTitle: 'Robert Fulghum' },
  { text: '“Head up, heart open. To better days!”',
    authorOrTitle: 'T.F. Hodge' },
  { text: '“Come friends, it\'s not too late to seek a newer world.”',
    authorOrTitle: 'Alfred Tennyson' },
  { text: '“The harder you fall, the heavier your heart; the heavier your heart, the stronger you climb; the stronger you climb, the higher your pedestal.”',
    authorOrTitle: 'Criss Jami' },
  { text: '“The heights by great men reached and kept were not attained in sudden flight but, they while their companions slept, they were toiling upwards in the night.”',
    authorOrTitle: 'Henry Wadsworth Longfellow' },
  { text: '“Thirty years ago my older brother, who was ten years old at the time, was trying to get a report written on birds that he\'d had three months to write, which was due the next day. We were out at our family cabin in Bolinas, and he was at the kitchen table close to tears, surrounded by binder paper and pencils and unopened books about birds, immobilized by the hugeness of the task ahead. Then my father sat down beside him put his arm around my brother\'s shoulder, and said, "Bird by bird, buddy. Just take it bird by bird.”',
    authorOrTitle: 'Anne Lamott' },
  { text: '“Be an Encourager: When you encourage others, you boost their self-esteem, enhance their self-confidence, make them work harder, lift their spirits and make them successful in their endeavors. Encouragement goes straight to the heart and is always available. Be an encourager. Always.”',
    authorOrTitle: 'Roy T. Bennett' },
  { text: '“...You can do something extraordinary, and something that a lot of people can\'t do. And if you have the opportunity to work on your gifts, it seems like a crime not to. I mean, it\'s just weakness to quit because something becomes too hard...”',
    authorOrTitle: 'Morgan Matson' },
  { text: '“A young outcast will often feel that there is something wrong with himself, but as he gets older, grows more confident in who he is, he will adapt, he will begin to feel that there is something wrong with everyone else.”',
    authorOrTitle: 'Criss Jami' },
  { text: '“Encouragement requires empathy and seeing the world from your spouse\'s perspective. We must first learn what is important to our spouse. Only then can we give encouragement. With verbal encouragement, we are trying to communicate, "I know. I care. I am with you. How can I help?" We are trying to show that we believe in him and in his abilities. We are giving credit and praise.”',
    authorOrTitle: 'Gary Chapman' },
  { text: '“Remember: It costs nothing to encourage an artist, and the potential benefits are staggering. A pat on the back to an artist now could one day result in your favorite film, or the cartoon you love to get stoned watching, or the song that saves your life. Discourage an artist, you get absolutely nothing in return, ever.”',
    authorOrTitle: 'Kevin Smith' },
  { text: '“Temptation is not to be feared, but controlled.”',
    authorOrTitle: 'Deborah Brodie' },
  { text: '“One word of encouragement can be enough to spark someone’s motivation to continue with a difficult challenge.”',
    authorOrTitle: 'Roy T. Bennett' },
  { text: '“With a hint of good judgment, to fear nothing, not failure or suffering or even death, indicates that you value life the most. You live to the extreme; you push limits; you spend your time building legacies. Those do not die.”',
    authorOrTitle: 'Criss Jami' } ]
